version: "3.2"
services:
  devin_postgres:
    image: postgres:latest
    container_name: 'DEVinHouse-pgsql'
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DATABASE: project4
    networks:
      - rabbitmq_go_net
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge